This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file /Users/diegofantinelli/Documents/LaTeX DoX/Overleaf Projects (4 items)/Report Template - MCyber/.texpadtmp/main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/diegofantinelli/Documents/LaTeX DoX/Overleaf Projects (4 items)/Report Template - MCyber/.texpadtmp/main.acn....done (6 entries accepted, 0 rejected).
Sorting entries....done (15 comparisons).
Generating output file /Users/diegofantinelli/Documents/LaTeX DoX/Overleaf Projects (4 items)/Report Template - MCyber/.texpadtmp/main.acr....done (10 lines written, 0 warnings).
Output written in /Users/diegofantinelli/Documents/LaTeX DoX/Overleaf Projects (4 items)/Report Template - MCyber/.texpadtmp/main.acr.
Transcript written in /Users/diegofantinelli/Documents/LaTeX DoX/Overleaf Projects (4 items)/Report Template - MCyber/.texpadtmp/main.alg.
